guests = ['David','Rob','Tommy','Vanessa','Leila','Kareem']

print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[0]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[1]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[2]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[3]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[4]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[5]))
print('\nHey everyone! We just found a bigger table so we can invite more people.')
guests.insert(0,'Spencer')
guests.insert(int(guests.__len__()/2),'Maria')
guests.insert(-1,'Ramon')

print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[0]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[1]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[2]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[3]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[4]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[5]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[6]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[7]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[8]))
print('\n')
print("Shoot! The table's late so we have to shrink the list")
print('\n')
print("Sorry {}! You wouldn't be able to join us on dinner. The table got messy. Next time maybe".format(guests.pop()))
print("Sorry {}! You wouldn't be able to join us on dinner. The table got messy. Next time maybe".format(guests.pop()))
print("Sorry {}! You wouldn't be able to join us on dinner. The table got messy. Next time maybe".format(guests.pop()))
print("Sorry {}! You wouldn't be able to join us on dinner. The table got messy. Next time maybe".format(guests.pop()))
print("Sorry {}! You wouldn't be able to join us on dinner. The table got messy. Next time maybe".format(guests.pop()))
print("Sorry {}! You wouldn't be able to join us on dinner. The table got messy. Next time maybe".format(guests.pop()))
print("Sorry {}! You wouldn't be able to join us on dinner. The table got messy. Next time maybe".format(guests.pop()))
print("{}".format(guests))

print('\n')
print("Hey {}! You are still invited.".format(guests[0]))
print("Hey {}! You are still invited.".format(guests[1]))
print("{} people are invited.".format(len(guests)))
del guests[0]
del guests[0]
print("{}".format(guests))