guests = ['David','Rob','Tommy','Vanessa','Leila','Kareem']

print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[0]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[1]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[2]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[3]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[4]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[5]))
print('\n\n\n')
print("Sorry guys! {} and {} will not be joining us on the dinner".format(guests.pop(),guests.pop()))
guests.append('Jordan')
guests.append('Lauren')
print('\n\n\n')
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[0]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[1]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[2]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[3]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[4]))
print("Hi {}! Will you honor me with being my guest for a dinner?".format(guests[5]))